name: Build and Publish

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      auto_deploy:
        description: auto deploy to devops-k8s
        type: boolean
        default: false

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.IMAGE_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get short commit SHA
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |
            BUILD_MODE=production
            VITE_ENVIRONMENT=${{ github.ref_name == 'main' && 'production' || 'dev' }}
            VITE_BACKEND_BASE_URL=/api
          push: true
          tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/protengplus-frontend:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' || github.event.inputs.auto_deploy == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get short commit SHA
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

      - name: Auto Deploy to devops-k8s
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ProtEngPlus
          repo: devops-k8s
          github_token: ${{ secrets.ACTIONS_AUTH_TOKEN }}
          github_user: protenger
          workflow_file_name: update-tag.yaml
          client_payload: ${{ format('{{"path":"{0}","tag":"{1}"}}', github.ref_name == 'main' && 'k8s/apps/protengplus-web/overlays/production/kustomization.yaml' || 'k8s/apps/protengplus-web/overlays/dev/kustomization.yaml', env.SHORT_SHA) }}
