name: Test Build Image

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short commit SHA
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}
          
      - name: Test Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: protengplus-frontend:${{ env.SHORT_SHA }}
