name: Test Build Image

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run format:check

      - name: ESLint
        run: npm run lint

  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short commit SHA
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

      - name: Test Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: protengplus-frontend:${{ env.SHORT_SHA }}
